name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker registry
        id: login
        uses: docker/login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t shamnarakuten/django-htmx-app .
      - name: Push Docker image
        run: docker push shamnarakuten/django-htmx-app
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to production
        run: docker run -p 8000:8000 shamnarakuten/django-htmx-app